[package]
name = "aoc2019"
version = "0.1.0"
authors = ["eiowlta <cassandra.l.mccord@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.18"
permutohedron = "0.2.4"
rayon = "1.2.1"